name: smart_pharma_net
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  http: ^1.2.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.1
  jwt_decoder: ^2.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.1
  flutter_advanced_segment: ^3.0.0
  geolocator_android: ^5.0.1+1
  geolocator_web: ^4.1.3

  # تم تحديث هذه المكتبة لحل مشكلة التوافق مع أندرويد
  speech_to_text: ^7.1.0

  image_picker: ^1.1.1

  # تم تحديث هذه المكتبة أيضًا لأنها كانت قديمة
  google_mlkit_text_recognition: ^0.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.1.0
  sensors_plus: ^6.1.1
  simple_animations: ^5.0.2
  flutter_svg: ^2.0.10+1
  lints: ^6.0.0
  string_similarity: ^2.0.0 # <--- أضف هذا السطر



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/welcome_img_screen.png
    - assets/icons/google.png
    - assets/icons/facebook-logo-in-circular-shape.png
    - assets/icons/apple-black-logo.png
    - assets/icons/menu-bar.png
    - assets/icons/search_icon.png
    - assets/icons/person.png
    - assets/icons/app_icon.png